---
# tasks file for ansible-role-nagios-nrpe
- name: Install NRPE packages
  yum:
    name: "{{ item }}""
    state: present
  with_items:
  - nrpe
  - nagios-plugins-users
  - nagios-plugins-load
  - nagios-plugins-swap
  - nagios-plugins-disk
  - nagios-plugins-procs

- name: Put NRPE daemon configuration in place
  template:
    src: templates/nrpe.j2
    dest: /etc/nagios/nrpe.cfg
    owner: nagios
    group: nagios
    mode: "u=rw,g=r,o=r"
 
- name: Put NRPE command definitions in place
  template:
    src: templates/rhel-base.j2
    dest: /etc/nrpe.d/rhel-base.cfg
    owner: nagios
    group: nagios
    mode: "u=rw,g=r,o=r"
     
- name: Set firewall rule for NRPE daemon
  firewalld:
    port: 5666/tcp
    permanent: true
    state: enabled
    
- name: Start and enable NRPE
  service:
    name: nrpe
    state: started
    enabled: yes
